optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 3000
  batch_size: 4096
  save_model: false
  loss: pairwise
  test_step: 3
  reproducible: true
  seed: 2024
  patience: 5

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20]
  batch_size: 1024

data:
  type: general_cf
  name: amazon

model:
  name: lightgcn_plus
  # general parameters here
  keep_rate: 0.8
  embedding_size: 32

  # dataset-specific parameters here
  layer_num: 3
  reg_weight: 1.0e-8
  kd_weight: 1.0e-3
  kd_temperature: 0.1
  steam:
    easyrec-roberta-large:
      layer_num: 3
      reg_weight: 1.0e-8
      kd_weight: 1.0e-2
      kd_temperature: 0.5